---
deployment:
  tasks:
    - /bin/echo "Starting deployment..."
    - /bin/rm -f /home1/wisdohkr/infinitekingdomguards.com/.htaccess
    - /bin/cp -ra dist/. /home1/wisdohkr/infinitekingdomguards.com/
    - /bin/rm -f /home1/wisdohkr/infinitekingdomguards.com/index.tsx
    - /bin/rm -rf /home1/wisdohkr/infinitekingdomguards.com/components
    - /bin/rm -rf /home1/wisdohkr/infinitekingdomguards.com/hooks
    - /bin/rm -rf /home1/wisdohkr/infinitekingdomguards.com/utils
    - /bin/chmod 755 /home1/wisdohkr/infinitekingdomguards.com
    - /bin/find /home1/wisdohkr/infinitekingdomguards.com -type d -exec chmod 755 {} \;
    - /bin/find /home1/wisdohkr/infinitekingdomguards.com -type f -exec chmod 644 {} \;
    - /bin/echo "Deployment complete."
